### ISSUE TITLE
Unable to use cordova version

### ISSUE THREAD

**Issue by raghavendradabbir** [SamVerschueren/gulp-cordova-version#10]
Hi, 

I am using the below in gulp
gulp.task('app.versionsetting', function () {
    return gulp.src('/')
        .pipe(create())
        .pipe(version('2.3.1'));
});

then in my cmd prompt, i am typing gulp app.versionsetting

I get the below and then no updates to the config file. Please help

D:\Work>gulp app.versionsetting
[00:22:49] Using gulpfile D:\Work\gulpfile.js
[00:22:49] Starting 'app.versionsetting'...

**Comment by SamVerschueren** [comment]
Can you provide me with the following information?

Where are you looking for your config file? Just to make sure you are looking at the right spot.

**Comment by raghavendradabbir** [comment]
Ok, maybe i am not looking at the right place - I did think abt this but wasnt sure - please let me know where I should find the config.xml - my concern is that the gulp task is starting but not ending. Here is what I am doing. My app workspace is 
D:\Work\
In this folder, I have a config.xml file and also my gulp.js.

**Comment by SamVerschueren** [comment]
The config.xml is created automatically together with the entire project. In your case, take a look in `D:\Work\.cordova`.

**Comment by raghavendradabbir** [comment]
I see a .cordova folder in the root. My project already has a config.xml and i am expecting the version to be updated in this file.
![test](https://cloud.githubusercontent.com/assets/13237337/15553227/c5968682-22db-11e6-96a3-36e17dcc5ebe.png)

**Comment by raghavendradabbir** [comment]
The .cordova folder is empty and contains no files

**Comment by SamVerschueren** [comment]
The [gulp-cordova](https://github.com/SamVerschueren/gulp-cordova) project is not meant for this use case. It is meant for creating a cordova build on different machines (throughout) your team without adding the config stuff to your repo or require everyone to have the cordova tools installed.

If you want this, you can either use [cordova-config](https://github.com/SamVerschueren/cordova-config) directly in your gulp task or create a custom plugin.

**Comment by SamVerschueren** [comment]
That indeed might be a bug.

**Comment by raghavendradabbir** [comment]
Thank u. I think cordova-config might help me. 

Thanks for ur support
