### ISSUE TITLE
Can't get it to set version based on gulp parameter

### ISSUE THREAD

**Issue by bc3tech** [SamVerschueren/gulp-cordova-version#9]
In my `gulpfile.js` I have

```
var cver = require('gulp-cordova-version');

gulp.task('default', ['setVersion']);

gulp.task('setVersion', function () {
    i = process.argv.indexOf("--setVersion");
    if (i > -1){
        version = process.argv[i+1];
        console.log('Setting app version to ' + version);
        cver(version);
    }
    else {
        console.log('Using version specified in config.xml for app versions...')
    }
});
```

and in my `gulp` output I get:

```
2016-04-19T15:59:38.222Z: [command]/usr/local/bin/gulp --gulpfile /Users/brandonh/djbuildagent-internal1/_work/13/s/gulpfile.js --setVersion 2016.0419.01
2016-04-19T15:59:42.409Z: Using gulpfile ~/djbuildagent-internal1/_work/13/s/gulpfile.js
2016-04-19T15:59:42.412Z: Starting 'setVersion'...
2016-04-19T15:59:42.413Z: Setting app version to 2016.0419.01
2016-04-19T15:59:42.415Z: [10:59:42] Finished 'setVersion' after 1.33 ms
```

yet my `config.xml` doesn't get its version set to the parameter shown (`2016.0419.01`)

Can you see anything wrong in what I'm doing? parameter is passed, picked up, and sent to `gulp-cordova-version` from what I can tell....

**Comment by SamVerschueren** [comment]
That's not how `gulp` works. It needs a source file. The easiest example in your case would be

``` js
var gulp = require('gulp');
var version = require('gulp-cordova-version');

gulp.task('build', function() {
    return gulp.src('project')
        .pipe(version('2.3.1'));
});
```

Where `project` is the root of your `cordova` project.

**Comment by bc3tech** [comment]
thanks. new to this gulp/npm stuff (obviously) - had a feeling I was doing something wrong. will close if this solves my issue

**Comment by bc3tech** [comment]
worked great. Thanks! do you have any plans to enable this to also change/add version tagging to `package.json` and `bower.json`?

**Comment by SamVerschueren** [comment]
Gulp has lot's of packages all focusing on "small" individual tasks. This one was created as part of a bigger group of plugins, namely [gulp-cordova](https://github.com/SamVerschueren/gulp-cordova). So as these are cordova specific, no extending this to support `package.json` would not fit the scope of the package. I am sure there are other packages that can do that for you :).

**Comment by bc3tech** [comment]
yeah I played with [gulp-cordova-bump](https://github.com/MichaelTaylor3D/gulp-cordova-bump) to do this but ran in to [a bug in libxml2js](https://github.com/polotek/libxmljs/issues/392) unfortunately. Yours looks to be kicking out the rightly-versioned binaries, though, so thanks!
